// Static mock data for UI display only.
// Replace with real API calls to the Chamaro Fastify backend later.
import type {
  AdminUser,
  B2BEnquiry,
  Banner,
  Category,
  Customer,
  MediaItem,
  Order,
  Product,
} from "./types";

export const mockProducts: Product[] = [
  {
    id: "p1",
    name: "Classic Cotton T-Shirt",
    image: "shirt",
    category: "Apparel",
    price: 24.0,
    compareAtPrice: 32.0,
    sku: "TS-CL-001",
    stock: 128,
    status: "Active",
    updatedAt: "2026-09-20",
    description: "A soft, breathable everyday t-shirt made from 100% combed cotton.",
    retailAvailable: true,
    b2bAvailable: true,
    moq: 50,
    b2bPricingNote: "Contact for quotation",
  },
  {
    id: "p2",
    name: "Leather Crossbody Bag",
    image: "bag",
    category: "Accessories",
    price: 89.0,
    sku: "BG-CB-014",
    stock: 12,
    status: "Active",
    updatedAt: "2026-09-18",
    description: "Handcrafted leather crossbody bag with adjustable strap.",
    retailAvailable: true,
    b2bAvailable: false,
  },
  {
    id: "p3",
    name: "Wireless Earbuds Pro",
    image: "earbuds",
    category: "Electronics",
    price: 129.99,
    compareAtPrice: 159.99,
    sku: "EL-EB-201",
    stock: 0,
    status: "Out of stock",
    updatedAt: "2026-09-15",
    description: "Active noise cancelling wireless earbuds with 30hr battery life.",
    retailAvailable: true,
    b2bAvailable: true,
    moq: 100,
    b2bPricingNote: "Contact for quotation",
  },
  {
    id: "p4",
    name: "Ceramic Coffee Mug Set",
    image: "mug",
    category: "Home",
    price: 34.5,
    sku: "HM-MG-090",
    stock: 64,
    status: "Active",
    updatedAt: "2026-09-12",
    description: "Set of 4 handmade ceramic mugs, dishwasher and microwave safe.",
    retailAvailable: true,
    b2bAvailable: true,
    moq: 200,
    b2bPricingNote: "Contact for quotation",
  },
  {
    id: "p5",
    name: "Running Shoes Flex",
    image: "shoe",
    category: "Footwear",
    price: 74.0,
    sku: "FW-RN-330",
    stock: 5,
    status: "Active",
    updatedAt: "2026-09-10",
    description: "Lightweight running shoes with breathable mesh upper.",
    retailAvailable: true,
    b2bAvailable: false,
  },
  {
    id: "p6",
    name: "Minimalist Wall Clock",
    image: "clock",
    category: "Home",
    price: 42.0,
    sku: "HM-CK-045",
    stock: 0,
    status: "Draft",
    updatedAt: "2026-09-05",
    description: "A silent-sweep wall clock with a minimalist walnut frame.",
    retailAvailable: true,
    b2bAvailable: false,
  },
  {
    id: "p7",
    name: "Denim Jacket",
    image: "jacket",
    category: "Apparel",
    price: 68.0,
    sku: "AP-DJ-112",
    stock: 41,
    status: "Active",
    updatedAt: "2026-08-30",
    description: "Classic fit denim jacket with button front closure.",
    retailAvailable: true,
    b2bAvailable: true,
    moq: 75,
    b2bPricingNote: "Contact for quotation",
  },
  {
    id: "p8",
    name: "Stainless Steel Water Bottle",
    image: "bottle",
    category: "Accessories",
    price: 19.99,
    sku: "AC-WB-077",
    stock: 3,
    status: "Active",
    updatedAt: "2026-08-28",
    description: "Insulated stainless steel bottle, keeps drinks cold for 24 hours.",
    retailAvailable: true,
    b2bAvailable: true,
    moq: 300,
    b2bPricingNote: "Contact for quotation",
  },
];

export const mockCategories: Category[] = [
  { id: "c1", name: "Apparel", slug: "apparel", productCount: 24, status: "Active", updatedAt: "2026-09-20" },
  { id: "c2", name: "Accessories", slug: "accessories", productCount: 15, status: "Active", updatedAt: "2026-09-18" },
  { id: "c3", name: "Electronics", slug: "electronics", productCount: 9, status: "Active", updatedAt: "2026-09-14" },
  { id: "c4", name: "Home", slug: "home", productCount: 18, status: "Active", updatedAt: "2026-09-10" },
  { id: "c5", name: "Footwear", slug: "footwear", productCount: 11, status: "Inactive", updatedAt: "2026-08-22" },
];

// Retail orders (customer → cart → checkout flow).
export const mockOrders: Order[] = [
  { id: "#10234", customer: "Ava Thompson", email: "ava.t@example.com", date: "2026-09-24", items: 3, total: 142.5, payment: "Paid", status: "Processing" },
  { id: "#10233", customer: "Liam Chen", email: "liam.chen@example.com", date: "2026-09-24", items: 1, total: 24.0, payment: "Paid", status: "Pending" },
  { id: "#10232", customer: "Sofia Ramirez", email: "sofia.r@example.com", date: "2026-09-23", items: 5, total: 268.4, payment: "Paid", status: "Shipped" },
  { id: "#10231", customer: "Noah Patel", email: "noah.p@example.com", date: "2026-09-23", items: 2, total: 98.0, payment: "Pending", status: "Confirmed" },
  { id: "#10230", customer: "Emma Wilson", email: "emma.w@example.com", date: "2026-09-22", items: 4, total: 176.25, payment: "Paid", status: "Completed" },
  { id: "#10229", customer: "Oliver Brown", email: "oliver.b@example.com", date: "2026-09-21", items: 1, total: 89.0, payment: "Refunded", status: "Cancelled" },
  { id: "#10228", customer: "Mia Davis", email: "mia.d@example.com", date: "2026-09-21", items: 2, total: 63.99, payment: "Paid", status: "Completed" },
  { id: "#10227", customer: "Ethan Garcia", email: "ethan.g@example.com", date: "2026-09-20", items: 6, total: 312.0, payment: "Failed", status: "Pending" },
];

export const mockBanners: Banner[] = [
  {
    id: "b1",
    image: "banner-autumn",
    title: "Autumn Collection Is Here",
    subtitle: "Discover cozy essentials for the season",
    buttonText: "Shop Now",
    buttonUrl: "/collections/autumn",
    order: 1,
    status: "Active",
    updatedAt: "2026-09-22",
    startAt: "2026-09-01T00:00",
    endAt: "2026-11-30T23:59",
  },
  {
    id: "b2",
    image: "banner-sale",
    title: "End of Season Sale",
    subtitle: "Up to 40% off selected items",
    buttonText: "View Deals",
    buttonUrl: "/sale",
    order: 2,
    status: "Active",
    updatedAt: "2026-09-15",
    startAt: "2026-09-10T00:00",
    endAt: "2026-10-10T23:59",
  },
  {
    id: "b3",
    image: "banner-new",
    title: "New Arrivals Weekly",
    subtitle: "Fresh styles added every Friday",
    buttonText: "Explore",
    buttonUrl: "/new",
    order: 3,
    status: "Inactive",
    updatedAt: "2026-08-30",
  },
];

export const mockMedia: MediaItem[] = [
  { id: "m1", name: "product-shirt-01.jpg", url: "shirt", type: "JPG", size: "482 KB", uploadedAt: "2026-09-20" },
  { id: "m2", name: "banner-autumn-hero.jpg", url: "banner-autumn", type: "JPG", size: "1.2 MB", uploadedAt: "2026-09-18" },
  { id: "m3", name: "product-bag-front.png", url: "bag", type: "PNG", size: "760 KB", uploadedAt: "2026-09-17" },
  { id: "m4", name: "product-earbuds.jpg", url: "earbuds", type: "JPG", size: "390 KB", uploadedAt: "2026-09-14" },
  { id: "m5", name: "category-home.jpg", url: "mug", type: "JPG", size: "540 KB", uploadedAt: "2026-09-10" },
  { id: "m6", name: "product-shoe-side.jpg", url: "shoe", type: "JPG", size: "610 KB", uploadedAt: "2026-09-08" },
  { id: "m7", name: "banner-sale-hero.jpg", url: "banner-sale", type: "JPG", size: "980 KB", uploadedAt: "2026-09-05" },
  { id: "m8", name: "product-jacket.jpg", url: "jacket", type: "JPG", size: "705 KB", uploadedAt: "2026-08-29" },
];

// Wholesale/B2B enquiries — a lead workflow, not a retail order workflow.
export const mockB2BEnquiries: B2BEnquiry[] = [
  {
    id: "ENQ-2041",
    companyName: "Urban Retail Group",
    contactPerson: "Daniel Osei",
    email: "daniel.osei@urbanretail.com",
    phone: "+1 (555) 234-1190",
    requirement: "Bulk apparel for staff uniforms",
    estimatedQuantity: 500,
    productsRequested: "Classic Cotton T-Shirt, Denim Jacket",
    notes: "Needs custom embroidery on chest logo.",
    expectedTimeline: "Within 6 weeks",
    date: "2026-09-22",
    status: "New",
  },
  {
    id: "ENQ-2040",
    companyName: "Northwind Hospitality",
    contactPerson: "Priya Nair",
    email: "priya.nair@northwindhotels.com",
    phone: "+1 (555) 887-2201",
    requirement: "Amenity kits for hotel rooms",
    estimatedQuantity: 1200,
    productsRequested: "Ceramic Coffee Mug Set, Stainless Steel Water Bottle",
    notes: "Recurring quarterly order if pilot succeeds.",
    expectedTimeline: "8-10 weeks",
    date: "2026-09-19",
    status: "Contacted",
  },
  {
    id: "ENQ-2039",
    companyName: "Fleetline Logistics",
    contactPerson: "Marcus Webb",
    email: "marcus.webb@fleetline.com",
    phone: "+1 (555) 410-7765",
    requirement: "Branded water bottles for driver welcome packs",
    estimatedQuantity: 800,
    productsRequested: "Stainless Steel Water Bottle",
    expectedTimeline: "4 weeks",
    date: "2026-09-16",
    status: "Requirement Received",
  },
  {
    id: "ENQ-2038",
    companyName: "Bright Path Schools",
    contactPerson: "Lena Ortiz",
    email: "lena.ortiz@brightpathschools.org",
    phone: "+1 (555) 665-9080",
    requirement: "Footwear for annual sports day",
    estimatedQuantity: 300,
    productsRequested: "Running Shoes Flex",
    expectedTimeline: "3 weeks",
    date: "2026-09-12",
    status: "Quotation Sent",
  },
  {
    id: "ENQ-2037",
    companyName: "Coastal Cafe Co.",
    contactPerson: "Ravi Shah",
    email: "ravi.shah@coastalcafe.com",
    phone: "+1 (555) 320-4471",
    requirement: "Mug sets for cafe retail counter",
    estimatedQuantity: 150,
    productsRequested: "Ceramic Coffee Mug Set",
    expectedTimeline: "Flexible",
    date: "2026-09-08",
    status: "Negotiating",
  },
  {
    id: "ENQ-2036",
    companyName: "Summit Corporate Gifts",
    contactPerson: "Hannah Lee",
    email: "hannah.lee@summitgifts.com",
    phone: "+1 (555) 902-3345",
    requirement: "Year-end client gifting",
    estimatedQuantity: 600,
    productsRequested: "Stainless Steel Water Bottle, Ceramic Coffee Mug Set",
    expectedTimeline: "5 weeks",
    date: "2026-08-30",
    status: "Converted",
  },
  {
    id: "ENQ-2035",
    companyName: "Alpine Outdoor Rentals",
    contactPerson: "Tom Fischer",
    email: "tom.fischer@alpinerentals.com",
    phone: "+1 (555) 118-6620",
    requirement: "Rental gear apparel",
    estimatedQuantity: 200,
    productsRequested: "Denim Jacket",
    expectedTimeline: "N/A",
    date: "2026-08-22",
    status: "Closed",
  },
];

export const mockCustomers: Customer[] = [
  {
    id: "cu1",
    name: "Ava Thompson",
    type: "Retail",
    email: "ava.t@example.com",
    phone: "+1 (555) 201-3344",
    status: "Active",
    joinedAt: "2025-11-02",
    ordersCount: 8,
    totalSpent: 642.35,
    recentOrders: [
      { id: "#10234", date: "2026-09-24", total: 142.5 },
      { id: "#10198", date: "2026-08-11", total: 76.0 },
    ],
  },
  {
    id: "cu2",
    name: "Liam Chen",
    type: "Retail",
    email: "liam.chen@example.com",
    phone: "+1 (555) 442-9981",
    status: "Active",
    joinedAt: "2026-01-14",
    ordersCount: 3,
    totalSpent: 158.4,
    recentOrders: [{ id: "#10233", date: "2026-09-24", total: 24.0 }],
  },
  {
    id: "cu3",
    name: "Sofia Ramirez",
    type: "Retail",
    email: "sofia.r@example.com",
    phone: "+1 (555) 765-2200",
    status: "Active",
    joinedAt: "2025-06-30",
    ordersCount: 15,
    totalSpent: 1284.9,
    recentOrders: [{ id: "#10232", date: "2026-09-23", total: 268.4 }],
  },
  {
    id: "cu4",
    name: "Urban Retail Group",
    type: "B2B",
    email: "daniel.osei@urbanretail.com",
    phone: "+1 (555) 234-1190",
    status: "Active",
    joinedAt: "2026-09-22",
    companyName: "Urban Retail Group",
    contactPerson: "Daniel Osei",
    enquiriesCount: 1,
    quotationStatus: "Awaiting first contact",
    recentActivity: [{ label: "Submitted enquiry ENQ-2041", date: "2026-09-22" }],
  },
  {
    id: "cu5",
    name: "Northwind Hospitality",
    type: "B2B",
    email: "priya.nair@northwindhotels.com",
    phone: "+1 (555) 887-2201",
    status: "Active",
    joinedAt: "2026-09-19",
    companyName: "Northwind Hospitality",
    contactPerson: "Priya Nair",
    enquiriesCount: 1,
    quotationStatus: "In discussion",
    recentActivity: [{ label: "Contacted by sales team", date: "2026-09-20" }],
  },
  {
    id: "cu6",
    name: "Summit Corporate Gifts",
    type: "B2B",
    email: "hannah.lee@summitgifts.com",
    phone: "+1 (555) 902-3345",
    status: "Active",
    joinedAt: "2026-08-30",
    companyName: "Summit Corporate Gifts",
    contactPerson: "Hannah Lee",
    enquiriesCount: 1,
    quotationStatus: "Converted to order",
    recentActivity: [
      { label: "Enquiry converted", date: "2026-09-05" },
      { label: "Quotation sent", date: "2026-09-01" },
    ],
  },
  {
    id: "cu7",
    name: "Alpine Outdoor Rentals",
    type: "B2B",
    email: "tom.fischer@alpinerentals.com",
    phone: "+1 (555) 118-6620",
    status: "Inactive",
    joinedAt: "2026-08-22",
    companyName: "Alpine Outdoor Rentals",
    contactPerson: "Tom Fischer",
    enquiriesCount: 1,
    quotationStatus: "Closed - no order",
    recentActivity: [{ label: "Enquiry closed", date: "2026-08-25" }],
  },
];

export const mockAdminUsers: AdminUser[] = [
  { id: "au1", name: "Chamaro Admin", email: "admin@chamaro.com", status: "Active", role: "ADMIN" },
  { id: "au2", name: "Priya Verma", email: "priya.verma@chamaro.com", status: "Active", role: "ADMIN" },
  { id: "au3", name: "James Carter", email: "james.carter@chamaro.com", status: "Inactive", role: "ADMIN" },
];

export const dashboardStats = {
  totalProducts: 90,
  retailOrders: 312,
  retailRevenue: 48920.5,
  customers: 1204,
  newB2bEnquiries: 4,
  activeB2bLeads: 12,
};

export const salesOverview = [
  { label: "Mon", value: 3200 },
  { label: "Tue", value: 4100 },
  { label: "Wed", value: 3800 },
  { label: "Thu", value: 5200 },
  { label: "Fri", value: 6100 },
  { label: "Sat", value: 7400 },
  { label: "Sun", value: 5800 },
];

export const lowStockProducts = mockProducts.filter((p) => p.stock > 0 && p.stock <= 15);
export const outOfStockProducts = mockProducts.filter((p) => p.stock === 0);
